/**
 * Unified Process deliverables, phase goals and a starter backlog.
 *
 * Due dates are expressed as "days before the phase gate" so the same template
 * works whether a phase is one sprint or six. Nothing here is mandatory - the
 * student can delete or add anything after generation - but it means a fresh
 * project already knows that a Vision Document belongs before LCO and a
 * Software Architecture Document before LCA.
 */
import type { Discipline, ItemType, PhaseKind } from '../types'

export interface ArtifactTemplate {
  name: string
  discipline: Discipline
  /** Due this many days before the phase's gate milestone. */
  dueBeforeGateDays: number
  description: string
  optional: boolean
}

export interface BacklogTemplate {
  title: string
  type: ItemType
  discipline: Discipline
  points: number
  estimateHours: number
  description: string
}

export const PHASE_GOALS: Record<PhaseKind, string> = {
  inception:
    'Define the problem, the scope and the success criteria. Identify the top risks and get the idea approved.',
  elaboration:
    'Retire the biggest technical risks with a running architectural skeleton and baseline the requirements.',
  construction: 'Build, test and integrate the remaining functionality sprint by sprint.',
  transition: 'Stabilise, document, rehearse the demo and hand in.'
}

export const ARTIFACT_TEMPLATES: Record<PhaseKind, ArtifactTemplate[]> = {
  inception: [
    {
      name: 'Vision Document',
      discipline: 'requirements',
      dueBeforeGateDays: 3,
      description:
        'The problem, who has it, what the system will do about it, and how you will know it worked.',
      optional: false
    },
    {
      name: 'Initial Use-Case Model',
      discipline: 'requirements',
      dueBeforeGateDays: 2,
      description:
        'Actors and the main use cases, with the two or three most important ones written out fully.',
      optional: false
    },
    {
      name: 'Risk List',
      discipline: 'project-management',
      dueBeforeGateDays: 2,
      description:
        'Ranked risks with a mitigation for each. Drives what you attack first in Elaboration.',
      optional: false
    },
    {
      name: 'Project Plan (this schedule)',
      discipline: 'project-management',
      dueBeforeGateDays: 1,
      description: 'Phases, sprints, milestones and your weekly time budget. Generated by this app.',
      optional: false
    },
    {
      name: 'Glossary',
      discipline: 'requirements',
      dueBeforeGateDays: 1,
      description: 'Domain terms, so the report and the code use the same words.',
      optional: true
    },
    {
      name: 'Development Environment Set Up',
      discipline: 'environment',
      dueBeforeGateDays: 1,
      description: 'Repository, toolchain, CI skeleton and a "hello world" that builds and runs.',
      optional: false
    }
  ],
  elaboration: [
    {
      name: 'Software Architecture Document',
      discipline: 'analysis-design',
      dueBeforeGateDays: 4,
      description:
        'The architecture in views: logical, process, deployment and data. Justify the key decisions.',
      optional: false
    },
    {
      name: 'Executable Architecture Baseline',
      discipline: 'implementation',
      dueBeforeGateDays: 2,
      description:
        'Running code that exercises the risky parts end to end. This is what the LCA gate really checks.',
      optional: false
    },
    {
      name: 'Refined Use-Case Model (80% baselined)',
      discipline: 'requirements',
      dueBeforeGateDays: 3,
      description: 'Most use cases identified and the architecturally significant ones detailed.',
      optional: false
    },
    {
      name: 'Domain / Analysis Model',
      discipline: 'analysis-design',
      dueBeforeGateDays: 3,
      description: 'Class diagram of the domain concepts and their relationships.',
      optional: false
    },
    {
      name: 'Test Plan',
      discipline: 'test',
      dueBeforeGateDays: 2,
      description: 'What you will test, at what level, and what "done" means for a story.',
      optional: false
    },
    {
      name: 'Updated Risk List',
      discipline: 'project-management',
      dueBeforeGateDays: 1,
      description: 'Which risks are now retired, and what replaced them.',
      optional: false
    }
  ],
  construction: [
    {
      name: 'Feature-Complete Build',
      discipline: 'implementation',
      dueBeforeGateDays: 3,
      description: 'All planned use cases implemented and integrated.',
      optional: false
    },
    {
      name: 'Test Report',
      discipline: 'test',
      dueBeforeGateDays: 2,
      description: 'Test results and coverage, plus the known-defect list.',
      optional: false
    },
    {
      name: 'User Documentation Draft',
      discipline: 'deployment',
      dueBeforeGateDays: 2,
      description: 'How someone else installs and uses the thing.',
      optional: false
    },
    {
      name: 'Report - Analysis & Design Chapters',
      discipline: 'analysis-design',
      dueBeforeGateDays: 5,
      description:
        'Write the report as you go. These chapters are cheapest to write while the work is fresh.',
      optional: false
    },
    {
      name: 'Continuous Integration Green',
      discipline: 'configuration-management',
      dueBeforeGateDays: 3,
      description: 'Build and tests running automatically on every push.',
      optional: true
    }
  ],
  transition: [
    {
      name: 'Final Report',
      discipline: 'project-management',
      dueBeforeGateDays: 3,
      description: 'Complete, proofread and formatted to the course template.',
      optional: false
    },
    {
      name: 'Release Package / Deployment',
      discipline: 'deployment',
      dueBeforeGateDays: 2,
      description: 'Installable build or deployed instance, with install instructions.',
      optional: false
    },
    {
      name: 'Defect Fixes from Feedback',
      discipline: 'implementation',
      dueBeforeGateDays: 4,
      description: 'Act on supervisor and user feedback from the IOC demo.',
      optional: false
    },
    {
      name: 'Presentation / Demo Script',
      discipline: 'deployment',
      dueBeforeGateDays: 2,
      description: 'Slides and a rehearsed walkthrough of the demo, timed.',
      optional: false
    },
    {
      name: 'Project Retrospective',
      discipline: 'project-management',
      dueBeforeGateDays: 0,
      description: 'What worked, what did not, what you would do differently. Often graded.',
      optional: true
    }
  ]
}

/** A small, honest starter backlog so the board is not empty on day one. */
export const BACKLOG_TEMPLATES: Record<PhaseKind, BacklogTemplate[]> = {
  inception: [
    {
      title: 'Write the vision and problem statement',
      type: 'task',
      discipline: 'requirements',
      points: 3,
      estimateHours: 4,
      description: 'One page: problem, users, proposed solution, success criteria.'
    },
    {
      title: 'Identify actors and draft the use-case diagram',
      type: 'task',
      discipline: 'requirements',
      points: 3,
      estimateHours: 4,
      description: 'Who uses the system and what they need from it.'
    },
    {
      title: 'Build the initial risk list',
      type: 'task',
      discipline: 'project-management',
      points: 2,
      estimateHours: 2,
      description: 'Rank by impact x likelihood; pick the top three to attack in Elaboration.'
    },
    {
      title: 'Set up repository, toolchain and CI skeleton',
      type: 'task',
      discipline: 'environment',
      points: 3,
      estimateHours: 4,
      description: 'Version control, build, formatter, test runner, a pipeline that runs them.'
    },
    {
      title: 'Agree scope and plan with supervisor',
      type: 'task',
      discipline: 'project-management',
      points: 1,
      estimateHours: 1,
      description: 'Book the meeting, bring the vision and the plan, write down what was agreed.'
    }
  ],
  elaboration: [
    {
      title: 'Spike: prove the riskiest technical assumption',
      type: 'spike',
      discipline: 'implementation',
      points: 5,
      estimateHours: 8,
      description: 'Timeboxed experiment against risk #1. Throwaway code is fine; the answer is not.'
    },
    {
      title: 'Draft the Software Architecture Document',
      type: 'task',
      discipline: 'analysis-design',
      points: 5,
      estimateHours: 8,
      description: 'Views, key decisions and why the alternatives were rejected.'
    },
    {
      title: 'Build the executable architecture skeleton',
      type: 'story',
      discipline: 'implementation',
      points: 8,
      estimateHours: 12,
      description: 'One thin slice running through every layer of the real architecture.'
    },
    {
      title: 'Detail the architecturally significant use cases',
      type: 'task',
      discipline: 'requirements',
      points: 3,
      estimateHours: 5,
      description: 'Main and alternate flows for the use cases that shape the design.'
    },
    {
      title: 'Write the test plan and the first automated tests',
      type: 'task',
      discipline: 'test',
      points: 3,
      estimateHours: 5,
      description: 'Levels, tooling, definition of done - and prove it by testing the skeleton.'
    }
  ],
  construction: [
    {
      title: 'Implement core use case #1',
      type: 'story',
      discipline: 'implementation',
      points: 8,
      estimateHours: 12,
      description: 'Replace with the real story once the backlog is filled in.'
    },
    {
      title: 'Implement core use case #2',
      type: 'story',
      discipline: 'implementation',
      points: 8,
      estimateHours: 12,
      description: 'Replace with the real story once the backlog is filled in.'
    },
    {
      title: 'Write the design chapters of the report',
      type: 'task',
      discipline: 'analysis-design',
      points: 5,
      estimateHours: 8,
      description: 'Writing while building is far cheaper than writing at the end.'
    },
    {
      title: 'Raise test coverage on the core modules',
      type: 'task',
      discipline: 'test',
      points: 3,
      estimateHours: 5,
      description: 'Focus on the logic an examiner would poke at.'
    }
  ],
  transition: [
    {
      title: 'Fix defects found in the IOC demo',
      type: 'bug',
      discipline: 'implementation',
      points: 5,
      estimateHours: 8,
      description: 'Triage first: fix what a reviewer will see.'
    },
    {
      title: 'Finish and proofread the final report',
      type: 'task',
      discipline: 'project-management',
      points: 8,
      estimateHours: 12,
      description: 'Leave a full day between finishing and proofreading.'
    },
    {
      title: 'Package the release and write install instructions',
      type: 'task',
      discipline: 'deployment',
      points: 3,
      estimateHours: 4,
      description: 'Verify it runs on a machine that is not yours.'
    },
    {
      title: 'Rehearse the presentation end to end',
      type: 'task',
      discipline: 'deployment',
      points: 2,
      estimateHours: 3,
      description: 'Out loud, timed, with the real demo. Twice.'
    }
  ]
}
